@echo off
set debug.event.output[alrdybss]=Bossness is not layerable.
set debug.event.output[alrdysmshbox]=You did this already...
set debug.event.output[alreadybx]=Urna apertus est.
set debug.event.output[already]=This door is already unlocked.
set debug.event.output[boss]=You're a boss.
set debug.event.output[bxsmshd]=Um... not happening.
set debug.event.output[disintegrate]=The key disintegrated.
set debug.event.output[implosion]=The box implodes under the might of your magical hammer.
set debug.event.output[lckdbxsmsh]=Well, it was locked...
set debug.event.output[mgic2]=Your hammer is now MAGIC
set debug.event.output[mgic]=You cast the magic on the hammer.
set debug.event.output[smashbx]=Smashed.
set debug.event.output[unlockbx]=The box opened.
set debug.event.output[unlock]=The door unlocked :D
set debug.event[1]=unlock
set debug.event[2]=open
set debug.event[3]=smash
set debug.event[4]=pull
set debug.event[5]=enchant
set debug.stencil[10].property[state]=1
set debug.stencil[1].property[protection]=1
set debug.stencil[2].property[condition]=1
set debug.stencil[3].property[colour]=2
set debug.stencil[3].property[condition]=3
set debug.stencil[3].property[imploded]=4
set debug.stencil[3].property[protection]=1
set debug.stencil[4].property[imploded]=1
set debug.stencil[5].property[enchanted]=2
set debug.stencil[5].property[state]=1
set debug.stencil[6].property[magical]=1
set debug.stencil[7].property[colour]=1
set debug.stencil[8].property[colour]=1
set debug.stencil[8].property[state]=2
set debug.stencil[9].property[colour]=1
set debug.stencil[9].property[state]=2
set place=room
set interpret.adjective[black].stencil[3]=2
set interpret.adjective[black].stencil[3].property=2
set interpret.adjective[blue].stencil[7]=2
set interpret.adjective[blue].stencil[7].property=1
set interpret.adjective[blue].stencil[8]=2
set interpret.adjective[blue].stencil[8].property=1
set interpret.adjective[blue].stencil[9]=2
set interpret.adjective[blue].stencil[9].property=1
set interpret.adjective[boring].stencil[5]=1
set interpret.adjective[boring].stencil[5].property=2
set interpret.adjective[boring].stencil[6]=1
set interpret.adjective[boring].stencil[6].property=1
set interpret.adjective[brown].stencil[3]=0
set interpret.adjective[brown].stencil[3].property=2
set interpret.adjective[closed].stencil[10]=0
set interpret.adjective[closed].stencil[10].property=1
set interpret.adjective[closed].stencil[9]=1
set interpret.adjective[closed].stencil[9].property=2
set interpret.adjective[enchanted].stencil[5]=0
set interpret.adjective[enchanted].stencil[5].property=2
set interpret.adjective[fragile].stencil[2]=1
set interpret.adjective[fragile].stencil[2].property=1
set interpret.adjective[green].stencil[7]=1
set interpret.adjective[green].stencil[7].property=1
set interpret.adjective[green].stencil[8]=1
set interpret.adjective[green].stencil[8].property=1
set interpret.adjective[green].stencil[9]=1
set interpret.adjective[green].stencil[9].property=1
set interpret.adjective[imploded].stencil[3]=0
set interpret.adjective[imploded].stencil[3].property=4
set interpret.adjective[imploded].stencil[4]=0
set interpret.adjective[imploded].stencil[4].property=1
set interpret.adjective[intact].stencil[3]=0
set interpret.adjective[intact].stencil[3].property=3
set interpret.adjective[locked].stencil[1]=1
set interpret.adjective[locked].stencil[1].property=1
set interpret.adjective[locked].stencil[3]=1
set interpret.adjective[locked].stencil[3].property=1
set interpret.adjective[magical].stencil[6]=0
set interpret.adjective[magical].stencil[6].property=1
set interpret.adjective[open].stencil[9]=0
set interpret.adjective[open].stencil[9].property=2
set interpret.adjective[pulled].stencil[8]=0
set interpret.adjective[pulled].stencil[8].property=2
set interpret.adjective[red].stencil[7]=0
set interpret.adjective[red].stencil[7].property=1
set interpret.adjective[red].stencil[8]=0
set interpret.adjective[red].stencil[8].property=1
set interpret.adjective[red].stencil[9]=0
set interpret.adjective[red].stencil[9].property=1
set interpret.adjective[smashed].stencil[3]=1
set interpret.adjective[smashed].stencil[3].property=3
set interpret.adjective[stable].stencil[2]=0
set interpret.adjective[stable].stencil[2].property=1
set interpret.adjective[sturdy].stencil[5]=0
set interpret.adjective[sturdy].stencil[5].property=1
set interpret.adjective[unlocked].stencil[1]=0
set interpret.adjective[unlocked].stencil[1].property=1
set interpret.adjective[unlocked].stencil[3]=0
set interpret.adjective[unlocked].stencil[3].property=1
set interpret.adjective[unpulled].stencil[8]=1
set interpret.adjective[unpulled].stencil[8].property=2
set interpret.adjective[weak].stencil[5]=1
set interpret.adjective[weak].stencil[5].property=1
set interpret.adjective[white].stencil[3]=1
set interpret.adjective[white].stencil[3].property=2
set interpret.hook.action[enchant]=5
set interpret.hook.action[open]=2
set interpret.hook.action[pull]=4
set interpret.hook.action[smash]=3
set interpret.hook.action[unlock]=1
set interpret.stencil[box]=3
set interpret.stencil[door]=1
set interpret.stencil[hammer]=5
set interpret.stencil[handle]=4
set interpret.stencil[hand]=10
set interpret.stencil[key]=2
set interpret.stencil[lever]=8
set interpret.stencil[magic]=6
set interpret.stencil[panel]=9
set interpret.stencil[secret]=7
set console.stencil[10]=hand
set console.stencil[10].property[1].adjective[0]=closed
set console.stencil[1]=door
set console.stencil[1].property[1].adjective[0]=unlocked
set console.stencil[1].property[1].adjective[1]=locked
set console.stencil[2]=key
set console.stencil[2].property[1].adjective[0]=stable
set console.stencil[2].property[1].adjective[1]=fragile
set console.stencil[3]=box
set console.stencil[3].property[1].adjective[0]=unlocked
set console.stencil[3].property[1].adjective[1]=locked
set console.stencil[3].property[2].adjective[0]=brown
set console.stencil[3].property[2].adjective[1]=white
set console.stencil[3].property[2].adjective[2]=black
set console.stencil[3].property[3].adjective[0]=intact
set console.stencil[3].property[3].adjective[1]=smashed
set console.stencil[3].property[4].adjective[0]=imploded
set console.stencil[4]=handle
set console.stencil[4].property[1].adjective[0]=imploded
set console.stencil[5]=hammer
set console.stencil[5].property[1].adjective[0]=sturdy
set console.stencil[5].property[1].adjective[1]=weak
set console.stencil[5].property[2].adjective[0]=enchanted
set console.stencil[5].property[2].adjective[1]=boring
set console.stencil[6]=magic
set console.stencil[6].property[1].adjective[0]=magical
set console.stencil[6].property[1].adjective[1]=boring
set console.stencil[7]=secret
set console.stencil[7].property[1].adjective[0]=red
set console.stencil[7].property[1].adjective[1]=green
set console.stencil[7].property[1].adjective[2]=blue
set console.stencil[8]=lever
set console.stencil[8].property[1].adjective[0]=red
set console.stencil[8].property[1].adjective[1]=green
set console.stencil[8].property[1].adjective[2]=blue
set console.stencil[8].property[2].adjective[0]=pulled
set console.stencil[8].property[2].adjective[1]=unpulled
set console.stencil[9]=panel
set console.stencil[9].property[1].adjective[0]=red
set console.stencil[9].property[1].adjective[1]=green
set console.stencil[9].property[1].adjective[2]=blue
set console.stencil[9].property[2].adjective[0]=open
set console.stencil[9].property[2].adjective[1]=closed
set stencil=10
set stencilcounter=10
set stencil[10].properties=1
set stencil[1].properties=1
set stencil[2].properties=1
set stencil[3].properties=4
set stencil[4].properties=1
set stencil[5].properties=2
set stencil[6].properties=1
set stencil[7].properties=1
set stencil[8].properties=2
set stencil[9].properties=2
set object=hammer
set object.location[1]=in the wall
set object.location[2]=on the floor
set object.location[3]=on the ground
set object.location[4]=on the box
set object.location[5]=in your hand
set object.location[6]=floating magically above your head
set object.location[7]=on the wall
set object.location[8]=on the wall
set object.location[9]=on your arm
set objectcounter=9
set object[1]=1
set object[1].property[1]=1
set object[2]=2
set object[2].property[1]=1
set object[3]=3
set object[3].property[1]=1
set object[3].property[2]=0
set object[4]=4
set object[5]=5
set object[5].property[1]=0
set object[5].property[2]=1
set object[6]=6
set object[6].property[1]=0
set object[7]=8
set object[7].property[1]=1
set object[7].property[2]=1
set object[8]=9
set object[8].property[1]=1
set object[8].property[2]=1
set object[9]=10
set eventcounter=5
set eventcounter.outs=3
set event[1]=?@1.$1=#1{!@1.$1=#0;?@2.$1=#1{~2;:1;}:2;}{:3;}
set event[1].instrument=2
set event[1].object=1
set event[1].output[1]=The key disintegrated.
set event[1].output[2]=The door unlocked :D
set event[1].output[3]=This door is already unlocked.
set event[2]=?@1.$1=#1{?@1.$3=#1{:1;}{!@1.$1=#0;:2;}}{:3;}
set event[2].instrument=4
set event[2].object=3
set event[2].output[1]=Um... not happening.
set event[2].output[2]=The box opened.
set event[2].output[3]=Urna apertus est.
set event[3]=?@1.$3=#0{?@2.$2=#0{!@1.$4=#0;!@1.$3=#1;:1;}{!@1.$1=#0;!@1.$3=#1;:2;}}{:3;}
set event[3].instrument=5
set event[3].object=3
set event[3].output[1]=The box implodes under the might of your magical hammer.
set event[3].output[2]=Well, it was locked...
set event[4]=?@1.$2=#1{!@1.$2=#0;:1;}{:2;}
set event[4].instrument=10
set event[4].object=8
set event[4].output[1]=You're a boss.
set event[4].output[2]=Bossness is not layerable.
set event[5]=?@1.$2=#1{!@1.$2=#0;:1;:2;}{:3;}
set event[5].instrument=6
set event[5].object=5
set event[5].output[1]=You cast the magic on the hammer.
set event[5].output[2]=Your hammer is now MAGIC
set hook.action[1].using[1,2]=1
set hook.action[2].using[3,4]=2
set hook.action[3].using[3,5]=3
set hook.action[4].using[8,10]=4
set hook.action[5].using[5,6]=5
start avencha.bat
