@echo off 
set $adj=locked
set $adjcounter=2
set $adjmax=2
set $counter=3
set $debug=person
set $max=3
set $pointer=person
set $pointid=4
set $points=3
set $pointtype=player
set $property=state
set $props=1
set $term=locked
set $type=5
set $value=2
set action=4
set bit=u
set cid=6
set compareop=mirrors
set COMSPEC=C:\Windows\system32\cmd.exe
set console.type[1]=space
set console.type[2]=object
set console.type[3]=key
set console.type[4]=player
set console.type[4].property[1].adjective[1]=hacker
set console.type[4].property[1].adjective[2]=chronologuer
set console.type[5]=wedge
set console.type[5].property[1].adjective[1]=open
set console.type[5].property[1].adjective[2]=locked
set console.type[6]=door
set console.type[6].property[1].adjective[1]=open
set console.type[6].property[1].adjective[2]=locked
set data=3
set debug=Lyre
set debug.event[enter]=2
set debug.event[unlock]=1
set debug.object[door]=4
set debug.object[in]=1
set debug.object[key]=5
set debug.object[Lyre]=3
set debug.object[out]=2
set debug.type[2].pointer[1].name=location
set debug.type[2].pointer[location]=1
set debug.type[3].pointer[1].name=location
set debug.type[3].pointer[location]=1
set debug.type[4].pointer[1].name=location
set debug.type[4].pointer[location]=1
set debug.type[4].property[1].name=type
set debug.type[4].property[type]=1
set debug.type[5].pointer[1].name=in
set debug.type[5].pointer[2].name=out
set debug.type[5].pointer[3].name=person
set debug.type[5].pointer[in]=1
set debug.type[5].pointer[out]=2
set debug.type[5].pointer[person]=3
set debug.type[5].property[1].name=state
set debug.type[5].property[state]=1
set debug.type[6].pointer[1].name=in
set debug.type[6].pointer[2].name=out
set debug.type[6].pointer[3].name=person
set debug.type[6].pointer[in]=1
set debug.type[6].pointer[out]=2
set debug.type[6].pointer[person]=3
set debug.type[6].property[1].name=state
set debug.type[6].property[state]=1
set dream.environment.events=2
set dream.environment.objects=5
set dream.environment.types=6
set dtype=pointer
set event=1
set eventname=unlock
set event[1]=?@1.@.$1=#2{!@1.@.$1=#1;-2;:1;:2;}{?@1.@.$1=#1{:3;?@1.3.$1=#1{:4;}?@1.3.$1=#2{:5;}}{:6;}}
set event[1].object=6
set event[1].output[1]=You hear some munching noises.
set event[1].output[2]=The door opened, but it ate the key.
set event[1].output[3]=The door is open, AND it previously ate the key you're unlocking it with.
set event[1].output[4]=Hacker.
set event[1].output[5]=Time traveller.
set event[1].output[6]=Whaaaaaa?
set event[1].subject=4
set event[2]=?@1.@.$1=#1{?@0.1.@=@1.1.@{!@0.1.@=@1.2.@;:1;}{?@0.1.@=@1.2.@{!@0.1.@=@1.1.@;:2;}{:3;}}}{:4;}
set event[2].object=6
set event[2].output[1]=You quested through the $ob to the outside.
set event[2].output[2]=You quested through the $ob to the inside.
set event[2].output[3]=You're not near the $ob.
set event[2].output[4]=The $ob is locked.
set event[2].subject=4
set foot=Lyre
set head=person
set hook.actions=4
set hook.action[1].using[6.]=2
set hook.action[2].using[6.]=2
set hook.action[3].using[6.]=1
set hook.action[4].using[6.]=1
set hook.controlgroup=3
set id=3
set indent=0
set interpret.adjective[chronologuer].type[4]=2
set interpret.adjective[chronologuer].type[4].property=1
set interpret.adjective[hacker].type[4]=1
set interpret.adjective[hacker].type[4].property=1
set interpret.adjective[locked].type[5]=2
set interpret.adjective[locked].type[5].property=1
set interpret.adjective[locked].type[6]=2
set interpret.adjective[locked].type[6].property=1
set interpret.adjective[open].type[5]=1
set interpret.adjective[open].type[5].property=1
set interpret.adjective[open].type[6]=1
set interpret.adjective[open].type[6].property=1
set interpret.hook.action[cross]=2
set interpret.hook.action[enter]=1
set interpret.hook.action[open]=3
set interpret.hook.action[unlock]=4
set interpret.type[door]=6
set interpret.type[key]=3
set interpret.type[nul]=0
set interpret.type[object]=2
set interpret.type[player]=4
set interpret.type[space]=1
set interpret.type[wedge]=5
set layer=-1
set layer[2]=else
set layer[3]=else
set layer[4]=else
set left=subject.location
set lhs=subject.location
set name=reality
set name[0]=enter
set ob=6
set object=door
set object[1]=1
set object[2]=1
set object[3]=4
set object[3].pointer[1]=1
set object[3].property[1]=2
set object[4]=6
set object[4].pointer[1]=1
set object[4].pointer[2]=2
set object[4].pointer[3]=3
set object[4].property[1]=2
set object[5]=3
set part=object
set partid=2
set partname=object
set parttype=6
set PATH=C:\Program Files (x86)\Blue Coat\ProxyClient\;
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.JS;.WS;.MSC
set place=room
set pointid=3
set pointname=in
set PROMPT=$P$G
set property=1
set purpose[0]=reality
set purpose[1]=defineobject
set purpose[2]=eventdata
set purpose[3]=eventdata
set purpose[4]=eventdata
set rhs=object.out
set right=4
set slot=3
set steeze=unlock unlock
set subject=player
set test=4
set this=enter player door
set thisid=0
set token=print
set type=controlhook
set type[0].sub=1;2;5;
set type[1].super=0
set type[2].pointers=1
set type[2].pointer[1]=1
set type[2].sub=3;4;
set type[2].super=0
set type[3].pointers=1
set type[3].pointer[1]=1
set type[3].super=2
set type[4].pointers=1
set type[4].pointer[1]=1
set type[4].properties=1
set type[4].property[1].highest=2
set type[4].super=2
set type[5].pointers=3
set type[5].pointer[1]=1
set type[5].pointer[2]=1
set type[5].pointer[3]=4
set type[5].properties=1
set type[5].property[1].highest=2
set type[5].sub=6;
set type[5].super=0
set type[6].pointers=3
set type[6].pointer[1]=1
set type[6].pointer[2]=1
set type[6].pointer[3]=4
set type[6].properties=1
set type[6].property[1].highest=2
set type[6].super=5
set useop=
set verb=unlock
if exist "Avencha.bat" (
 Avencha.bat
) else (
 pushd ..
 if exist "Avencha.bat" (
  Avencha.bat
 ) else (
  echo This needs to be in the same directory as Avencha ^>,^<
  echo     ^(Or . . . at least in a subdirectory of such a directory^)
  echo.
  echo Press any key to exit . . .
  pause>nul
 )
)
